--- #YAML:1.0
name:                SOAP-Lite
version:             0.710.05
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Compress::Zlib:                0
    Crypt::SSLeay:                 0
    FCGI:                          0
    HTTP::Daemon:                  0
    IO::File:                      0
    IO::Socket::SSL:               0
    LWP::UserAgent:                0
    MIME::Base64:                  0
    MIME::Lite:                    0
    MIME::Parser:                  0
    Net::FTP:                      0
    Net::POP3:                     0
    Scalar::Util:                  0
    Test::More:                    0
    URI:                           0
    version:                       0
    XML::Parser:                   2.23
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
